apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-creds
  labels:
    {{- include "tenant-init.labels" . | nindent 4 }}
type: Opaque
data:
  host: {{ .Values.postgres.host | b64enc }}
  port: {{ .Values.postgres.port | b64enc }}
  admin-user: {{ .Values.postgres.user | b64enc }}
  admin-password: {{ .Values.postgres.password | b64enc }}
  ssl-mode: {{ .Values.postgres.sslmode | b64enc }}
  tenant-password: {{ default (randAlphaNum 16) .Values.tenant.postgresPassword | b64enc }} 