{{- if .Values.tenant.createRole }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tenant.name }}
  namespace: {{ include "tenant.namespace" . }}
  labels:
    {{- include "tenant.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.accountId }}:role/{{ .Values.tenant.name }}-sync-role
{{- end }} 