{{- if .Values.cloudwatch.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
  labels:
  {{- include "cloudquery.labels" . | nindent 4 }}
data:
  cluster.name: {{ .Values.cloudwatch.cluster_name }}
  http.server: "Off"
  http.port: ""
  read.head: "Off"
  read.tail: "On"
  logs.region: {{ .Values.cloudwatch.region }}
{{- end }}