apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cloudquery.fullname" . }}-pvc
  labels:
    {{- include "cloudquery.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi