{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
{{- with .Values.serviceAccount.autoMount }}
automountServiceAccountToken: {{ . }}
{{- end }}
metadata:
  name: {{ include "cloudquery.serviceAccountName" . }}
  labels:
    {{- include "cloudquery.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
