receivers:
  otlp:
    protocols:
      http:
        endpoint: :4318
processors:
  filter:
    logs:
      log_record:
        - 'IsMatch(body, "table resolver finished with error|table sync finished|table resolver finished with panic") == false'

  batch:
    send_batch_size: 100000
    timeout: 5s

exporters:
  nop:
  clickhouse:
    endpoint: ${env:CLICKHOUSE_DSN}
    database: ${env:CLICKHOUSE_DATABASE}
    create_schema: true
    cluster_name: ${env:OTEL_CLUSTER_NAME:-}
    table_engine:
      name: ${env:OTEL_TABLE_ENGINE_NAME:-MergeTree}
      params: ${env:OTEL_TABLE_ENGINE_PARAMS:-}
    ttl: 0
    timeout: 10s
    sending_queue:
      queue_size: 100
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

extensions:
  zpages:
    endpoint: 0.0.0.0:55679
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [ health_check, zpages ]
  pipelines:
    logs:
      receivers: [ otlp ]
      processors: [ filter, batch ]
      exporters: [ clickhouse ]
    traces:
      receivers: [ otlp ]
      processors: [ filter, batch ]
      exporters: [ clickhouse ]
    metrics:
      receivers: [ otlp ]
      processors:
      exporters: [ nop ]
