# -- The number of replicas to deploy
replicaCount: 1

image:
  # -- The image repository to pull from
  repository: us-east1-docker.pkg.dev/cq-cloud-prod/platform/full
  # -- (string) Overrides the image tag whose default is the chart appVersion
  tag:
  pullPolicy: IfNotPresent

# -- Override the default name
nameOverride: ""
# -- Override the full name
fullNameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

# -- Addition pod annotations
podAnnotations: {}

# -- Addition pod labels
podLabels: {}

podDisruptionBudget:
  minAvailable: 1

# -- Specify the pod-level security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 3001
  seccompProfile:
    type: RuntimeDefault

# -- Specify the container-level security context
containerSecurityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all

# -- Specify the ports the container exposes
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  annotations: {}

# -- Specify the scheduler configuration
scheduler:
  address: scheduler-operator:3001

# -- Deployment resources
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  periodSeconds: 60
  httpGet:
    path: /
    port: api
readinessProbe:
  periodSeconds: 30
  httpGet:
    path: /
    port: api

persistence:
  enabled: false

  # Keep existing fields at the top level for backward compatibility
  # These will be used for EBS storage (default)
  type: "gp2"
  accessModes:
    - ReadWriteOnce
  size: 100Gi
  annotations: {}

  # New field to select storage type
  # When not specified, defaults to "EBS" for backward compatibility
  mode: "EBS"

  # New S3 specific configuration section
  s3:
    bucketName: "my-application-data"
    region: "us-east-1"
    # S3-specific settings
    mountOptions:
      - "uid=1000"
      - "gid=1000"

# -- Additional volumes on the output Deployment definition.
volumes:
  - name: tmp
    emptyDir: {}

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: tmp
    mountPath: /tmp

# -- Platform secrets configuration
platformSecrets:
  # -- Required: The secret reference to use for the user-supplied platform secrets
  secretRef: "cq-platform-secrets"

# -- External secrets configuration
externalSecrets:
  # -- Optional. Enable external secrets.
  enabled: false
  # -- Required: The AWS region where the secrets are stored
  region: ""
  # -- Required: The AWS secret key for the Postgres DSN
  cloudquerySecretsKey: ""
  # -- Required: The AWS role ARN to assume when fetching the secrets
  externalSecretsRoleARN: ""

letsEncrypt:
  # -- Optional. Enable Let's Encrypt.
  enabled: false
  # -- Required: The email address to use for Let's Encrypt
  email: ""

# -- OTEL Collector configuration
otelCollector:
  # -- Optional. Enable the OTEL Collector.
  enabled: true
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.121.0"
    pullPolicy: IfNotPresent

  # -- Optional. The database to use for the ClickHouse exporter (should match the ClickHouse DSN)
  database: "default"

  podDisruptionBudget:
    minAvailable: 1

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  livenessProbe:
    periodSeconds: 60
    httpGet:
      path: /
      port: 13133
  readinessProbe:
    periodSeconds: 30
    httpGet:
      path: /
      port: 13133

  service:
    type: ClusterIP
    ports:
      - name: otlp-grpc
        port: 4317
        protocol: TCP
        targetPort: 4317
      - name: otlp-http
        port: 4318
        protocol: TCP
        targetPort: 4318

  # -- Specify the pod-level security context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    seccompProfile:
      type: RuntimeDefault

  # -- Specify the container-level security context
  containerSecurityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  # -- Optional. Enable ingress.
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: local.cloudquery.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: local-cloudquery-io-tls
  #    hosts:
  #      - local.cloudquery.io

debug:
  # -- Optional. Enable debug mode.
  enabled: false

# -- ClickHouse configuration for cluster support
clickhouse:
  # -- Whether ClickHouse is running in a clustered environment
  isCluster: false
  # -- ClickHouse cluster name (required when isCluster is true)
  clusterName: ""

# -- Init Container configuration
# @section Init Containers
# @descriptionStart
# Configuration for initialization containers that run before the main application.
# These containers handle database connectivity checks and schema initialization.
# @descriptionEnd
initContainers:
  # -- Enable or disable initialization containers
  enabled: true
  # -- Image pull policy for init containers
  imagePullPolicy: IfNotPresent

  # -- Configuration for the curl container used to initialize ClickHouse
  curl:
    # -- Container image repository for curl
    repository: curlimages/curl
    # -- Container image tag for curl
    tag: 8.5.0

  # -- Configuration for the netcat container used for connectivity checks
  netcat:
    # -- Container image repository for netcat
    repository: toolbelt/netcat
    # -- Container image tag for netcat
    tag: latest

  # -- Security context for init containers
  # @schemaRef SecurityContext
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 10001
    capabilities:
      drop:
        - ALL

  # -- Retry configuration for connectivity checks
  retry:
    # -- Maximum number of retry attempts for connectivity checks
    maxAttempts: 5
    # -- Time to wait between retry attempts (in seconds)
    interval: 5

  # -- Timeout configuration for database operations
  timeout:
    # -- Connection timeout for database checks (in seconds)
    connect: 5
    # -- Operation timeout for database operations (in seconds)
    operation: 10

# -- Testing secret configuration - only used during CI/CD
testingSecret:
  enabled: false
  activationKey: ""
  postgresqlDSN: ""
  clickhouseDSN: ""
  rudderstackBackendWriteKey: ""
  rudderstackFrontendWriteKey: ""
