# -- The number of replicas to deploy
replicaCount: 1

image:
  # -- The image repository to pull from
  repository: us-east1-docker.pkg.dev/cq-cloud-prod/platform/full
  # -- (string) Overrides the image tag whose default is the chart appVersion
  tag:
  pullPolicy: IfNotPresent

# -- Override the default name
nameOverride: ""
# -- Override the full name
fullNameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

# -- Addition pod annotations
podAnnotations: {}

# -- Addition pod labels
podLabels: {}

# -- Specify the pod-level security context
podSecurityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 3001
  runAsGroup: 3001
  fsGroup: 3001

# -- Specify the container-level security context
containerSecurityContext: {}

# -- Specify the ports the container exposes
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
  annotations: {}

# -- Specify the scheduler configuration
scheduler:
  address: scheduler-operator:3001

# -- Deployment resources
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  periodSeconds: 60
  httpGet:
    path: /
    port: api
readinessProbe:
  periodSeconds: 30
  httpGet:
    path: /
    port: api

# -- Additional volumes on the output Deployment definition.
volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
  - name: tmp
    emptyDir: {}
  - name: shared
    emptyDir: {}

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: nginx-config
    mountPath: /etc/nginx/nginx.conf
    subPath: nginx.conf
  - name: tmp
    mountPath: /tmp/platform
  - name: shared
    mountPath: /shared

# -- Platform secrets configuration
platformSecrets:
  # -- Required: The secret reference to use for the user-supplied platform secrets
  secretRef: "cq-platform-secrets"

  # -- JWT private key reference for the self-hosted platform - if not provided, a new key will be generated
  jwtPrivateKeyRef: ""

# -- External secrets configuration
externalSecrets:
  # -- Optional. Enable external secrets.
  enabled: false
  # -- Required: The AWS region where the secrets are stored
  region: ""
  # -- Required: The AWS secret key for the Postgres DSN
  cloudquerySecretsKey: ""
  # -- Required: The AWS role ARN to assume when fetching the secrets
  externalSecretsRoleARN: ""

letsEncrypt:
  # -- Optional. Enable Let's Encrypt.
  enabled: false
  # -- Required: The email address to use for Let's Encrypt
  email: ""

# -- OTEL Collector configuration
otelCollector:
  # -- Optional. Enable the OTEL Collector.
  enabled: true
  image:
    repository: otel/opentelemetry-collector-contrib
    tag: "0.113.0"
    pullPolicy: IfNotPresent

  # -- Optional. The database to use for the ClickHouse exporter (should match the ClickHouse DSN)
  database: "default"

  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 1
    #   memory: 2Gi
    # requests:
    #   cpu: 200m
    #   memory: 400Mi

  service:
    type: ClusterIP
    ports:
      - name: otlp-grpc
        port: 4317
        protocol: TCP
        targetPort: 4317
      - name: otlp-http
        port: 4318
        protocol: TCP
        targetPort: 4318

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  # -- Optional. Enable ingress.
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: local.cloudquery.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: local-cloudquery-io-tls
  #    hosts:
  #      - local.cloudquery.io

debug:
  # -- Optional. Enable debug mode.
  enabled: false

# -- Testing secret configuration - only used during CI/CD
testingSecret:
  enabled: false
  activationKey: ""
  postgresqlDSN: ""
  clickhouseDSN: ""
