---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/log
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - update
- apiGroups:
  - scheduling.cloudquery.io
  resources:
  - connectiontests
  - syncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.cloudquery.io
  resources:
  - connectiontests/finalizers
  - syncs/finalizers
  verbs:
  - update
- apiGroups:
  - scheduling.cloudquery.io
  resources:
  - connectiontests/status
  - syncs/status
  verbs:
  - get
  - patch
  - update
