apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullName" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: application
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: application
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: application
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "platform.serviceAccount" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers.enabled }}
      initContainers:
        - name: init-connectivity
          image: {{ .Values.initContainers.netcat.repository }}:{{ .Values.initContainers.netcat.tag }}
          imagePullPolicy: {{ .Values.initContainers.imagePullPolicy }}
          command:
            - /bin/sh
            - /scripts/check-connectivity.sh
          env:
            - name: MAX_ATTEMPTS
              value: {{ .Values.initContainers.retry.maxAttempts | quote }}
            - name: RETRY_INTERVAL
              value: {{ .Values.initContainers.retry.interval | quote }}
            - name: CONNECT_TIMEOUT
              value: {{ .Values.initContainers.timeout.connect | quote }}
          securityContext:
            {{- toYaml .Values.initContainers.securityContext | nindent 12 }}
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
              readOnly: true
            - name: platform-secrets
              mountPath: /secrets
              readOnly: true
        - name: init-clickhouse
          image: {{ .Values.initContainers.curl.repository }}:{{ .Values.initContainers.curl.tag }}
          imagePullPolicy: {{ .Values.initContainers.imagePullPolicy }}
          command:
            - /usr/bin/env
            - sh 
            - /scripts/init-clickhouse.sh
          env:
            - name: MAX_ATTEMPTS
              value: {{ .Values.initContainers.retry.maxAttempts | quote }}
            - name: RETRY_INTERVAL
              value: {{ .Values.initContainers.retry.interval | quote }}
            - name: OPERATION_TIMEOUT
              value: {{ .Values.initContainers.timeout.operation | quote }}
          securityContext:
            {{- toYaml .Values.initContainers.securityContext | nindent 12 }}
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
              readOnly: true
            - name: platform-secrets
              mountPath: /secrets
              readOnly: true
      {{- end }}
      containers:
        - name: platform
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ include "platform.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "platform.fullName" . }}-config
          env:
            - name: CQAPI_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.secretRef" . }}
                  key: postgresqlDSN
            - name: CQAPI_LOCAL_ACTIVATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.secretRef" . }}
                  key: activationKey
            - name: CQAPI_WAREHOUSE_CLICKHOUSE_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.secretRef" . }}
                  key: clickhouseDSN
            - name: CQAPI_LOCAL_JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "platform.jwtPrivateKeyRef" . }}
                  key: jwtPrivateKey
          ports:
            - name: proxy
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            - name: ui
              containerPort: 3001
              protocol: TCP
            - name: api
              containerPort: 4444
              protocol: TCP
            - name: storage
              containerPort: 4445
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: storage
              mountPath: /data/storage
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "platform.fullName" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- if .Values.initContainers.enabled }}
        - name: init-scripts
          configMap:
            name: {{ include "platform.fullName" . }}-init-scripts
            defaultMode: 0755
        - name: platform-secrets
          secret:
            secretName: {{ include "platform.secretRef" . }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
