{{- if .Values.otelCollector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform.fullName" . }}-otel-collector
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      annotations:
        {{- with .Values.otelCollector.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          args:
            - --config=/conf/collector.yaml
          env:
            - name: CLICKHOUSE_DSN
              valueFrom:
                secretKeyRef:
                  {{- if index .Values "externalSecrets" "enabled" }}
                  name: {{ include "platform.fullName" . }}-external-secrets
                  {{- else }}
                  name: {{ include "platform.fullName" . }}-secrets
                  {{- end }}
                  key: clickhouseDSN
            - name: CLICKHOUSE_DATABASE
              value: {{ .Values.otelCollector.database }}
          ports:
            {{- range .Values.otelCollector.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol }}
            {{- end }}
          resources:
            {{- toYaml .Values.otelCollector.resources | nindent 12 }}
          volumeMounts:
            - name: collector-config
              mountPath: /conf
      volumes:
        - name: collector-config
          configMap:
            name: {{ include "platform.fullName" . }}-otel-collector-config
{{- end }}
