{{- if and .Values.persistence.enabled (eq (.Values.persistence.mode | default "EBS") "S3") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "platform.fullName" . }}-s3-pv
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: {{ .Release.Namespace }} # Namespace is required even though it's in "default" namespace.
    name: {{ include "platform.fullName" . }}-s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region {{ .Values.persistence.s3.region }}
    - prefix /
    {{- range .Values.persistence.s3.mountOptions }}
    - {{ . }}
    {{- end }}
    - allow-other
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: {{ .Values.persistence.s3.bucketName }}
{{- end }}