{{- if and .Values.persistence.enabled (eq (.Values.persistence.mode | default "EBS") "EBS") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "platform.fullName" . }}-pvc
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: {{ include "platform.fullName" . }}-sc
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
---
{{- if and .Values.persistence.enabled (eq (.Values.persistence.mode | default "EBS") "S3") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "platform.fullName" . }}-s3-pvc
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: s3-pv # Name of your PV
{{- end }}