apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullName" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if not (index .Values "externalSecrets" "enabled") }}
  {{- if .Values.activationKey }}
  activationKey: {{ .Values.activationKey | b64enc }}
  {{- end }}
  postgresqlDSN: {{ required "A valid postgres DSN is required" .Values.externalDependencies.postgresql_dsn | b64enc }}
  clickhouseDSN: {{ required "A valid clickhouse DSN is required" .Values.externalDependencies.clickhouse_dsn | b64enc }}
  {{- end }}
  jwtPrivateKey: {{ .Values.jwtPrivateKey | default (genPrivateKey "rsa") | b64enc }}
---
{{- if index .Values "externalSecrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "platform.fullName" . }}-external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ include "platform.fullName" . }}-external-secrets
    creationPolicy: Owner
  data:
    - secretKey: activationKey
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: activation_key
    - secretKey: postgresqlDSN
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: connection_string
    - secretKey: clickhouseDSN
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: clickhouse_dsn
{{- end }}
