{{- if not (index .Values "platformSecrets" "jwtPrivateKeyRef") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullName" . }}-jwt-private-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  jwtPrivateKey: {{ (genPrivateKey "rsa") | b64enc }}
---
{{- end }}
{{- if index .Values "externalSecrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "platform.fullName" . }}-external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ include "platform.fullName" . }}-external-secrets
    creationPolicy: Owner
  data:
    - secretKey: activationKey
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: activation_key
    - secretKey: postgresqlDSN
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: connection_string
    - secretKey: clickhouseDSN
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: clickhouse_dsn
{{- end }}
