{{- if .Values.testingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.platformSecrets.secretRef}}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  activationKey: {{ .Values.testingSecret.activationKey | b64enc }}
  postgresqlDSN: {{ .Values.testingSecret.postgresqlDSN | b64enc }}
  clickhouseDSN: {{ .Values.testingSecret.clickhouseDSN | b64enc }}
  privateKey: {{ (genPrivateKey "rsa") | b64enc }}
  rudderstack_backend_write_key: {{ .Values.testingSecret.rudderstackBackendWriteKey | b64enc }}
  rudderstack_frontend_write_key: {{ .Values.testingSecret.rudderstackFrontendWriteKey | b64enc }}
---
{{- end}}
{{- if index .Values "externalSecrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "platform.fullName" . }}-external-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ include "platform.fullName" . }}-external-secrets
    creationPolicy: Owner
  data:
    - secretKey: activationKey
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: activation_key
    - secretKey: postgresqlDSN
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: connection_string
    - secretKey: clickhouseDSN
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: clickhouse_dsn
    - secretKey: privateKey
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: private_key
    - secretKey: rudderstackBackendWriteKey
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: rudderstack_backend_write_key
    - secretKey: rudderstackFrontendWriteKey
      remoteRef:
        key: {{ required "externalSecrets.cloudquerySecretsKey is required" (index .Values "externalSecrets" "cloudquerySecretsKey") }}
        property: rudderstack_frontend_write_key
{{- end }}
