apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullName" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.activationKey }}
  activationKey: {{ .Values.activationKey | b64enc }}
  {{- end }}
  postgresqlDSN: {{ required "A valid postgres DSN is required" .Values.externalDependencies.postgresql_dsn | b64enc }}
  clickhouseDSN: {{ required "A valid clickhouse DSN is required" .Values.externalDependencies.clickhouse_dsn | b64enc }}
  jwtPrivateKey: |
    {{ genPrivateKey "rsa" | b64enc }}
