{{- if index .Values "externalSecrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ required "externalSecrets.region is required" (index .Values "externalSecrets" "region") }}
      auth:
        jwt:
          serviceAccountRef:
            name: aws-secrets-manager
{{- end }}
