apiVersion: v1
kind: Secret
metadata:
  name: {{ include "platform.fullName" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.activationKey }}
  activationKey: {{ .Values.activationKey | b64enc }}
  {{- end }}
  {{- if not (index .Values "external-secrets" "enabled") }}
  postgresqlDSN: {{ required "A valid postgres DSN is required" .Values.externalDependencies.postgresql_dsn | b64enc }}
  {{- end }}
  clickhouseDSN: {{ required "A valid clickhouse DSN is required" .Values.externalDependencies.clickhouse_dsn | b64enc }}
  jwtPrivateKey: {{ .Values.jwtPrivateKey | default (genPrivateKey "rsa") | b64enc }}
---
{{- if index .Values "external-secrets" "enabled" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "platform.fullName" . }}-connection-string
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: {{ include "platform.fullName" . }}-connection-string
    creationPolicy: Owner
  data:
    - secretKey: postgres_connection_string
      remoteRef:
        key: {{ required "external-secrets.postgresSecretKey is required" (index .Values "external-secrets" "postgresSecretKey") }}
        property: connection_string
{{- end }}
