apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullName" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: application
---
{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "opentelemetry-collector"
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.otelCollector.service.type }}
  ports:
    {{- range .Values.otelCollector.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
{{- end }}