{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform.serviceAccount" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
{{- if index .Values "externalSecrets" "enabled" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-manager
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "externalSecrets.externalSecretsRoleARN is required" (index .Values "externalSecrets" "externalSecretsRoleARN") }}
  {{- with index .Values "externalSecrets" "annotations" }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
