{{- if index .Values "external-secrets" "enabled" -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-manager
  labels:
    {{- include "platform.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "external-secrets.externalSecretsRoleARN is required" (index .Values "external-secrets" "externalSecretsRoleARN") }}
  {{- with index .Values "external-secrets" "annotations" }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
