apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullName" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.proxyType }}
  ports:
    - port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
      name: proxy
  selector:
    {{- include "platform.selectorLabels" . | nindent 4 }}
