apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudquery.name" . }}-admin
  labels:
  {{- include "cloudquery.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cloudquery.selectorLabels" . | nindent 12 }}
  template:
    metadata:
      labels:
      {{- include "cloudquery.selectorLabels" . | nindent 12 }}
    spec:
      containers:
        - name: cloudquery
          envFrom:
          - secretRef:
              name: {{ include "cloudquery.name" . }}-secret
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          # we want users to be able to exec into this pod and be able to debug and investigate cloudquery binary, envs and runtime
          args: ["-c", "echo admin container is running. run 'kubectl exec -it deploy/cloudquery-admin -- /bin/sh' to debug; while true; do sleep 10000; done"]
          resources:
          {{- toYaml .Values.resources | nindent 16 }}
          volumeMounts:
          - name: config
            mountPath: /app/config
          - name: cq
            mountPath: /app/.cq
      volumes:
      - name: cq
        persistentVolumeClaim:
          claimName: {{ template "cloudquery.name" . }}-pvc
      - name: config
        configMap:
          name: {{ include "cloudquery.name" . }}-config
          items:
          - key: config.hcl
            path: config.hcl
