apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudquery.name" . }}-config
  labels:
  {{- include "cloudquery.labels" . | nindent 4 }}
data:
  config.hcl: |-
  {{ .Files.Get "config.hcl" | nindent 4 }}
