apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudquery.name" . }}-secret
  labels:
  {{- include "cloudquery.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.envRenderSecret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
