name: Bump Terraform Chart Version
on: [push]
#release:
#types: [published]
jobs:
  bump-terraform-chart-version:
    name: Bump Terraform Chart Version
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout helm-charts source code'
        uses: 'actions/checkout@v3'
        with:
          path: helm-charts
      - name: 'Checkout terraform-aws-cloudquery source code'
        uses: 'actions/checkout@v3'
        with:
          path: terraform-aws-cloudquery
          repository: cloudquery/terraform-aws-cloudquery
          token: ${{ secrets.GH_PAT }}
      - name: 'Checkout terraform-gcp-cloudquery source code'
        uses: 'actions/checkout@v3'
        with:
          path: terraform-gcp-cloudquery
          repository: cloudquery/terraform-gcp-cloudquery
          token: ${{ secrets.GH_PAT }}
      - run: |
          HELM_CHART_VERSION=$(grep version: helm-charts/charts/cloudquery/Chart.yaml | cut -d\  -f2)
          echo "HELM_CHART_VERSION=$(echo $HELM_CHART_VERSION)" >> $GITHUB_ENV
          sed -i 's/^\(\s*\)default\(\s*\)=\(\s*\)\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\"\s*#\ Do\ not\ change\ CloudQuery\ helm\ chart\ version\ as\ it\ is\ automatically\ updated\ by\ Workflow\s*$/\1default\2=\3"'"$HELM_CHART_VERSION"'" # Do not change CloudQuery helm chart version as it is automatically updated by Workflow/' /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery/variables.tf
          sed -i 's/\(The\ version\ of\ CloudQuery\ helm\ chart\ | `string`\ | `"\)\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1'"$HELM_CHART_VERSION"'/' /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery/README.md
          sed -i 's/^\(\s*\)default\(\s*\)=\(\s*\)\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\"\s*#\ Do\ not\ change\ CloudQuery\ helm\ chart\ version\ as\ it\ is\ automatically\ updated\ by\ Workflow\s*$/\1default\2=\3"'"$HELM_CHART_VERSION"'" # Do not change CloudQuery helm chart version as it is automatically updated by Workflow/' /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery/variables.tf
          sed -i 's/\(The\ version\ of\ CloudQuery\ helm\ chart\ | `string`\ | `"\)\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1'"$HELM_CHART_VERSION"'/' /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery/README.md
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore: Bump CloudQuery helm chart version'
          committer: GitHub <noreply@github.com>
          author: CloudQuery Bot <102256036+cq-bot@users.noreply.github.com>
          signoff: false
          branch: chore/bump-terraform-chart-version-${{ env.HELM_CHART_VERSION }}
          delete-branch: true
          title: 'chore: Bump CloudQuery helm chart version'
          labels: |
            chore
            automerge
          assignees: cq-bot
          reviewers: cq-bot
          draft: false
          path: /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore: Bump CloudQuery helm chart version'
          committer: GitHub <noreply@github.com>
          author: CloudQuery Bot <102256036+cq-bot@users.noreply.github.com>
          signoff: false
          branch: chore/bump-terraform-chart-version-${{ env.HELM_CHART_VERSION }}
          delete-branch: true
          title: 'chore: Bump CloudQuery helm chart version'
          labels: |
            chore
            automerge
          assignees: cq-bot
          reviewers: cq-bot
          draft: false
          path: /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery