name: Bump Terraform Chart Version
on:
  release:
    types: [published]
jobs:
  bump-terraform-chart-version:
    name: Bump Terraform Chart Version
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout helm-charts source code'
        uses: 'actions/checkout@v3'
        with:
          path: helm-charts
      - name: 'Checkout terraform-aws-cloudquery source code'
        uses: 'actions/checkout@v3'
        with:
          path: terraform-aws-cloudquery
          repository: cloudquery/terraform-aws-cloudquery
          token: ${{ secrets.GH_CQ_BOT }}
      - name: 'Checkout terraform-gcp-cloudquery source code'
        uses: 'actions/checkout@v3'
        with:
          path: terraform-gcp-cloudquery
          repository: cloudquery/terraform-gcp-cloudquery
          token: ${{ secrets.GH_CQ_BOT }}
      - name: Bump Versions if required
        run: |
          # Bump Versions if required
          
          # Get the current version
          HELM_CHART_VERSION=$(grep version: helm-charts/charts/cloudquery/Chart.yaml | cut -d\  -f2)
          echo "HELM_CHART_VERSION=$(echo $HELM_CHART_VERSION)" >> $GITHUB_ENV
          HELM_CHART_MAJORMINOR_VERSION=$(echo $HELM_CHART_VERSION | sed 's/\([0-9]\+\.[0-9]\+\)\.[0-9]\+/\1/')

          # Get the current Helm Chart version in AWS
          AWS_HELM_CHART_MAJORMINOR_VERSION=$(grep 'default[ \t]*=[ \t]*"[0-9]\+\.[0-9]\+\.[0-9]\+"[ \t]*# Do not change CloudQuery helm chart version as it is automatically updated by Workflow' /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery/variables.tf | sed 's/^\s*default\s*=\s*\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\".*/\1/' | sed 's/\([0-9]\+\.[0-9]\+\)\.[0-9]\+/\1/')
          if [ "$HELM_CHART_MAJORMINOR_VERSION" != "$AWS_HELM_CHART_MAJORMINOR_VERSION" ]; then
            echo "Bumping AWS Terraform Helm Chart Version to $HELM_CHART_VERSION"
            # Replace the Helm Chart version in AWS
            sed -i 's/^\(\s*\)default\(\s*\)=\(\s*\)\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\"\s*#\ Do\ not\ change\ CloudQuery\ helm\ chart\ version\ as\ it\ is\ automatically\ updated\ by\ Workflow\s*$/\1default\2=\3"'"$HELM_CHART_VERSION"'" # Do not change CloudQuery helm chart version as it is automatically updated by Workflow/' /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery/variables.tf
            sed -i 's/\(The\ version\ of\ CloudQuery\ helm\ chart\ | `string`\ | `"\)\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1'"$HELM_CHART_VERSION"'/' /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery/README.md
          else
            echo "Skipping AWS Terraform Helm Chart Version bump since Major and Minor are the same"
          fi
          
          # Get the current Helm Chart version in GCP
          GCP_HELM_CHART_MAJORMINOR_VERSION=$(grep 'default[ \t]*=[ \t]*"[0-9]\+\.[0-9]\+\.[0-9]\+"[ \t]*# Do not change CloudQuery helm chart version as it is automatically updated by Workflow' /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery/variables.tf | sed 's/^\s*default\s*=\s*\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\".*/\1/' | sed 's/\([0-9]\+\.[0-9]\+\)\.[0-9]\+/\1/')
          if [ "$HELM_CHART_MAJORMINOR_VERSION" != "$GCP_HELM_CHART_MAJORMINOR_VERSION" ]; then
            echo "Bumping GCP Terraform Helm Chart Version to $HELM_CHART_VERSION"
            # Replace the Helm Chart version in GCP
            sed -i 's/^\(\s*\)default\(\s*\)=\(\s*\)\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\"\s*#\ Do\ not\ change\ CloudQuery\ helm\ chart\ version\ as\ it\ is\ automatically\ updated\ by\ Workflow\s*$/\1default\2=\3"'"$HELM_CHART_VERSION"'" # Do not change CloudQuery helm chart version as it is automatically updated by Workflow/' /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery/variables.tf
            sed -i 's/\(The\ version\ of\ CloudQuery\ helm\ chart\ | `string`\ | `"\)\([0-9]\+\.[0-9]\+\.[0-9]\+\)/\1'"$HELM_CHART_VERSION"'/' /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery/README.md
          else
            echo "Skipping GCP Terraform Helm Chart Version bump since Major and Minor are the same"
          fi
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_CQ_BOT }}
          commit-message: 'feat: Bump CloudQuery helm chart version'
          committer: GitHub <noreply@github.com>
          author: CloudQuery Bot <102256036+cq-bot@users.noreply.github.com>
          signoff: false
          branch: feat/bump-terraform-chart-version-${{ env.HELM_CHART_VERSION }}
          delete-branch: true
          title: 'feat: Bump CloudQuery helm chart version'
          labels: |
            feat
            automerge
          assignees: cq-bot
          reviewers: cq-bot
          draft: false
          path: /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_CQ_BOT }}
          commit-message: 'feat: Bump CloudQuery helm chart version'
          committer: GitHub <noreply@github.com>
          author: CloudQuery Bot <102256036+cq-bot@users.noreply.github.com>
          signoff: false
          branch: feat/bump-terraform-chart-version-${{ env.HELM_CHART_VERSION }}
          delete-branch: true
          title: 'feat: Bump CloudQuery helm chart version'
          labels: |
            feat
            automerge
          assignees: cq-bot
          reviewers: cq-bot
          draft: false
          path: /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery
