name: Bump Terraform Chart Version
on: [push]
#release:
#types: [published]
jobs:
  bump-terraform-chart-version:
    name: Bump Terraform Chart Version
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout helm-charts source code'
        uses: 'actions/checkout@v3'
        with:
          path: helm-charts
      - name: 'Checkout terraform-aws-cloudquery source code'
        uses: 'actions/checkout@v3'
        with:
          path: terraform-aws-cloudquery
          repository: cloudquery/terraform-aws-cloudquery
          token: ${{ secrets.GH_PAT }}
      - name: 'Checkout terraform-gcp-cloudquery source code'
        uses: 'actions/checkout@v3'
        with:
          path: terraform-gcp-cloudquery
          repository: cloudquery/terraform-gcp-cloudquery
          token: ${{ secrets.GH_PAT }}
      - run: |
          helm_chart_version=$(grep version: helm-charts/charts/cloudquery/Chart.yaml | cut -d\  -f2)
          sed -i 's/^\(\s*\)default\(\s*\)=\(\s*\)\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\"\s*#\ Do\ not\ change\ CloudQuery\ helm\ chart\ version\ as\ it\ is\ automatically\ updated\ by\ Workflow\s*$/\1default\2=\3"'"$helm_chart_version"'" # Do not change CloudQuery helm chart version as it is automatically updated by Workflow/' /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery/variables.tf
          sed -i 's/^\(\s*\)default\(\s*\)=\(\s*\)\"\([0-9]\+\.[0-9]\+\.[0-9]\+\)\"\s*#\ Do\ not\ change\ CloudQuery\ helm\ chart\ version\ as\ it\ is\ automatically\ updated\ by\ Workflow\s*$/\1default\2=\3"'"$helm_chart_version"'" # Do not change CloudQuery helm chart version as it is automatically updated by Workflow/' /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery/variables.tf
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore: Bump CloudQuery helm chart version'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: chore/bump-terraform-chart-version
          delete-branch: true
          title: 'chore: Bump CloudQuery helm chart version'
          labels: |
            chore
            automerge
          assignees: spangenberg
          reviewers: spangenberg
          team-reviewers: |
            cloudquery/cloudquery-opensource
          draft: false
          path: /home/runner/work/helm-charts/helm-charts/terraform-aws-cloudquery
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: 'chore: Bump CloudQuery helm chart version'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: chore/bump-terraform-chart-version
          delete-branch: true
          title: 'chore: Bump CloudQuery helm chart version'
          labels: |
            chore
            automerge
          assignees: spangenberg
          reviewers: spangenberg
          team-reviewers: |
            cloudquery/cloudquery-opensource
          draft: false
          path: /home/runner/work/helm-charts/helm-charts/terraform-gcp-cloudquery