name: Bumps versions and docs for dependencies updates

on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  bump:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'cq-bot' && startsWith(github.event.pull_request.title, 'fix(deps)')
    steps:
      - uses: actions/github-script@v7
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
        with:
          github-token: ${{ secrets.GH_CQ_BOT }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const { SHA: sha } = process.env;
            console.log({ issue_number, owner, repo, sha });
            await github.rest.issues.createComment({
              issue_number,
              owner,
              repo,
              body: `/bump sha=${sha}`
            })
