name: Release Please
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_CQ_BOT }}

      - name: Checkout
        uses: actions/checkout@v4
        if: |
          startsWith(github.event.head_commit.message, 'chore(main): Release')
        with:
          fetch-depth: 0

      - name: Configure Git
        if: |
          startsWith(github.event.head_commit.message, 'chore(main): Release')
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        if: |
          startsWith(github.event.head_commit.message, 'chore(main): Release')
        uses: azure/setup-helm@v4
        with:
          version: v3.8.1

      - name: Helm Deps
        if: |
          startsWith(github.event.head_commit.message, 'chore(main): Release')
        run: |
          helm repo add secrets-store-csi-driver https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run chart-releaser
        if: |
          startsWith(github.event.head_commit.message, 'chore(main): Release')
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
